### ISSUE TITLE
Animations at www.freepress.net

### ISSUE THREAD

**Issue by grahamperrin** [jnlon/disable-transitions#1]
Re: https://github.com/gagarine/no-transition/issues/24#issuecomment-568947656 

Can you think of a way for your extension to block the animations in this screen recording? 

- https://put.re/player/ffL8ur4M.mp4
- [2019-12-26 01:36.zip](https://github.com/jnlon/disable-transitions/files/4001092/2019-12-26.01.36.zip)

Thanks

**Comment by jnlon** [comment]
Hi! I looked at the website's code, it seems to be using JavaScript (jQuery) and CSS for animations. My extension only blocks static CSS animations because it is just a stylesheet, a js-based addon (like no-transition) is needed to prevent js/jquery animations.

When I loaded the page in your video I notice some effects are disabled by my addon but some remain. I think this is caused by jQuery's .animate() method used toward the bottom of [this file](https://www.freepress.net/sites/default/files/js/js_DHlxX9fKhj1MKVcZELrWZPCfy0We229pIAweZaOCREE.js).

Apparently [jQuery animations can be disabled by WebExtensions](https://github.com/gagarine/no-transition/issues/5). A PR fixing this bug might fix this site in particular, but I suspect blocking all JS animations in general for all sites without outright disabling JS is likely a hard problem.

I currently have no plans to extend this addon further due to my limited time and because it would involve essentially recreating no-transition. I can try submitting a PR to no-transition for this issue though since it doesn't look too difficult to fix (but maybe I'm wrong, no promises).

Either way, in your case I highly recommend using a general-purpose content blocker like [umatrix](https://addons.mozilla.org/en-US/firefox/addon/umatrix/?src=search) to block all JS/CSS by default and enabling on a per-site basis. It did this for a while and it works well after the initial adjustment. Good luck!
